### ISSUE TITLE
check for node version breaks app

### ISSUE THREAD

**Issue by hellno** [neynarxyz/nodejs-sdk#119]
herocast (https://github.com/hero-org/herocast) relies on the nodejs-sdk in the frontend. we're doing a bunch of requests to get data for feeds and channels from the frontend using `NeynarAPIClient`.

relevant commit: https://github.com/neynarxyz/nodejs-sdk/commit/292cf128d518d7b0fd865f5a678b243741cb1f53

error messages: 
<img width="581" alt="image" src="https://github.com/neynarxyz/nodejs-sdk/assets/686075/eb82322d-cf83-4c2d-9baa-4bdabe5fc9b8">

is there a recommended different way to make requests from frontend?
is there a quick improvement we can make to exclude the node version check if a request is made from frontend?

thank you! :)

**Comment by Shreyaschorge** [comment]
@hellno `@neynar/nodejs-sdk` should not be used from the frontend, because `NEYNAR_API_KEY` will be bundled and shipped in the frontend code, thus leaking the key

We would recommend to have a server running node `>= 19.9.0` and frontend should make a call to this server.

**Comment by hellno** [comment]
hm okay. not the best solution. 
most requests are unique feeds per user, so we're not benefitting from caching data on a server. so it'll mostly be additional request time from frontend <> server <> neyar API and back

**Comment by Shreyaschorge** [comment]
@hellno Oh no. Authorized origins are used only for SIWN right now.

**Comment by Shreyaschorge** [comment]
@hellno Closing this issue. Feel free to create a new one if needed
