### ISSUE TITLE
CastsResponseResults V2 is missing NextCursor

### ISSUE THREAD

**Issue by porenes** [neynarxyz/nodejs-sdk#163]
There should be a cursor here

https://github.com/neynarxyz/nodejs-sdk/blob/a7a6b4945bced6e2ca735adec7164fa48983198f/src/neynar-api/v2/openapi-farcaster/models/casts-response-result.ts#L32

**Comment by Shreyaschorge** [comment]
@porenes 

This model is used in methods like `fetchBulkCasts` and `searchCasts` and the cursor is not part of the response.
Are you looking for something else?
Please let me know which method you are using or type for which method you are looking for.

**Comment by porenes** [comment]
searchCasts API does have a cursor in the reply

![image](https://github.com/user-attachments/assets/c673d081-5f37-4890-bce5-4d7b9b5537a2)

**Comment by valerierose** [comment]
Fixed in v1.49.1 https://github.com/neynarxyz/nodejs-sdk/releases/tag/v1.49.1
