### ISSUE TITLE
Notification type is missing count

### ISSUE THREAD

**Issue by porenes** [neynarxyz/nodejs-sdk#172]
https://github.com/neynarxyz/nodejs-sdk/blob/698e1b4d16852fc6c04c570fca2dd875c15d880e/src/neynar-api/v2/openapi-farcaster/models/notification.ts#L74

the APi returns a 'count' value for notifications, it is missing in the Type

**Comment by Shreyaschorge** [comment]
@porenes Thanks for reporting

Following PR fixes it
https://github.com/neynarxyz/nodejs-sdk/pull/173
