### ISSUE TITLE
moderatorFids is missing from Channel type.

### ISSUE THREAD

**Issue by porenes** [neynarxyz/nodejs-sdk#179]
Channel infos now include moderatorFids: number[] , the type needs to be updated

https://github.com/neynarxyz/nodejs-sdk/blob/bec2e51dc436e81be9ca47e5922d41d184ffa09e/src/neynar-api/v2/openapi-farcaster/models/channel.ts#L28

**Comment by Shreyaschorge** [comment]
> Channel infos now include moderatorFids: number[] , the type needs to be updated
> 
> https://github.com/neynarxyz/nodejs-sdk/blob/bec2e51dc436e81be9ca47e5922d41d184ffa09e/src/neynar-api/v2/openapi-farcaster/models/channel.ts#L28

@porenes 
Yeah we are working on it, it should be out in a couple of hours

**Comment by porenes** [comment]
You rock !

**Comment by Shreyaschorge** [comment]
@porenes are you using `moderatorFids` anywhere in anyway?
Actually, a bug was introduced that the `moderatorFids` should have been snake_case but now it's camelCase.
I just want to gauge whether we can make a breaking change. If so, this release will need to be put on hold. Sorry for the wait.

**Comment by porenes** [comment]
It's not live yet, I am using it in my code to support the new channel model.
As I am using the SDK, I used a ts-expect-error, I assume that however the api is snake_case the Typescript type will use camelCase

**Comment by Shreyaschorge** [comment]
It'll be a breaking change in api since this API returns it as a camelCase. Will discuss it with the team and let you know.

**Comment by Shreyaschorge** [comment]
@porenes 

This should fix it. Please use snake_case.
https://github.com/neynarxyz/nodejs-sdk/pull/187
