### ISSUE TITLE
`fetchUserFollowersV2` has incorrect response type

### ISSUE THREAD

**Issue by alex-grover** [neynarxyz/nodejs-sdk#181]
The SDK (and [OAS spec](https://github.com/neynarxyz/OAS/blob/main/src/v2/spec.yaml#L6473)) indicates that the `fetchUserFollowersV2` endpoint returns a `UsersResponse`, but it actually returns a response with the following shape:

```
{
  users: {
    object: "follow",
    user: UserV2 // Nesting here is not reflected in the spec/types
  }[]
}
```

I haven't checked the other following APIs but it looks like they also have `UsersResponse` listed so they may be incorrect as well.

**Comment by Shreyaschorge** [comment]
Thanks for reporting

Following PR should fix it
https://github.com/neynarxyz/nodejs-sdk/pull/188
