### ISSUE TITLE
`respondChannelInvite` success, but not becoming member

### ISSUE THREAD

**Issue by zacharytyhacz** [neynarxyz/nodejs-sdk#186]
### Version
```
"@neynar/nodejs-sdk": "^1.58.0"
```

I am trying to accept a channel invite, but it is not working.
- [x] user is following the channel
- [x] i check if membership really went through through both api and warpcast client, both dont show that user is a member

### I get invites for our user's FID
```typescript
  export const getIntoriChannelInvites = async (): Promise<ChannelInviteType[]> => {
    try {
      const res = await warpcastApi.get(
        '/fc/channel-invites',
        {
          params: {
            fid: process.env.INTORI_USER_FID
          }
        }
      )

      return res.data?.result?.invites ?? []
    } catch (err) {
      console.error('Warpcast API error:', err)
      return []
    }
  }

```

### I am seeing a valid channel invite:
![image](https://github.com/user-attachments/assets/087e647f-dd39-40eb-97e7-9b2e4ed26096)

### respond to the invite, returns success and no message
```typescript
  export const acceptChannelInvite = async (params: {
    channelId: string
    role: 'moderator' | 'member'
  }) => {
    console.log('Accepting channel invite', params)
    return neynar.respondChannelInvite(
      process.env.NEYNAR_SIGNER_UUID ?? 'missing signer uuid',
      params.channelId,
      params.role,
      true
    )
  }
```

Response:
![image](https://github.com/user-attachments/assets/565a85d9-213f-46e0-bd1d-8cd23667856e)

### Invite goes away, but this user never becomes a member. Even after waiting 1+ hour

**Comment by zacharytyhacz** [comment]
> @zacharytyhacz Is the invited member following the channel they are being invited to?

Yes, the user is following the channel.

**Comment by manan19** [comment]
@zacharytyhacz thanks for the detailed ticket. As discussed on the call, the same process worked well when trying it again today. Seems like it could've been a transient bug, we'll reopen this ticket if it happens again.
