### ISSUE TITLE
Missing property pinnedCastHash for Channel type

### ISSUE THREAD

**Issue by porenes** [neynarxyz/nodejs-sdk#189]
https://github.com/neynarxyz/nodejs-sdk/blob/441317ddcbd6d8afa7b629b860fbeb4a58741598/src/neynar-api/v2/openapi-farcaster/models/channel.ts#L28

**Comment by Shreyaschorge** [comment]
@porenes 

This should fix it
https://github.com/neynarxyz/nodejs-sdk/releases/tag/v1.62.1
