### ISSUE TITLE
User.verified_addresses not part of interface

### ISSUE THREAD

**Issue by eucalyptus-viminalis** [neynarxyz/nodejs-sdk#75]
`verified_addresses` is not part of the `User` interface.

## Reproduce

_Typescript code_
```ts
    ...
    const data = await neynar.fetchBulkUsers([fid], {
        // viewerFid,
    })
    const user: User | undefined = data.users.at(0)
    if (user === undefined) {
        throw new Error('fetchBulkUsers failed for fid: ' + fid)
    }
    console.log('user', user)
    ...
```

_Intellisense_
<img width="599" alt="image" src="https://github.com/neynarxyz/nodejs-sdk/assets/65995595/4c76cded-b544-45f3-9ad8-0850f245e486">

_User object using `NeynarAPIClient.fetchBulkUsers`_
<img width="608" alt="image" src="https://github.com/neynarxyz/nodejs-sdk/assets/65995595/38166d2b-8bdb-4d26-befd-d7c60f4bb6b7">

Checking various `User` types that are part of the SDK, we see that `verified_addresses` is not part of the `User` interface. 

## Additional discussion
Is is possible to narrow the export scope for types in the SDK? Problem with this is that I'm not sure if the `XYZ` type/interface have the same shape in all the different files that export the same symbol name. This could lead developers to sink time in checking all the different exported symbols to verify if they're importing the wrong thing.

E.g. If I try to import `SomeType` in VSCode using "Quick Fix," I'm overwhelmed by exports from many different files.

_VSCode Quick Fix_
<img width="801" alt="image" src="https://github.com/neynarxyz/nodejs-sdk/assets/65995595/016bcdcc-e8b1-447a-862b-eb399d0e714c">

**Comment by Shreyaschorge** [comment]
@eucalyptus-viminalis 

Thanks for reporting.

`verified_addresses` is now a part of the `User` interface. 
https://github.com/neynarxyz/nodejs-sdk/releases/tag/v1.11.1

Also added a ticket for centralizing exports in the backlog. I'll revisit this once I get some time.

Marking this issue as closed feel free to re-open this if needed or create another one.
