### ISSUE TITLE
publishCast - AxiosError 400

### ISSUE THREAD

**Issue by ggomaeng** [neynarxyz/nodejs-sdk#88]
Trying to publish cast non english cast like below

```ts
const { hash } = await client.publishCast(FARCASTER_UUID, "NeoPetsのリードエンジニアでした (2000年10月 - 2002年11月)", {
      replyTo: lastHash,   
});
```

crashes with:

`AxiosError: Request failed with status code 400`

**Comment by manan19** [comment]
@ggomaeng Do you have the response object alongside with the 400 response object? Are you able to reproduce this 100% of the time? I was able to send a cast with the exact text you mentioned https://warpcast.com/~/conversations/0xf45653331e2d5c128654e9c5a09303fb4aebb979

**Comment by ggomaeng** [comment]
> @ggomaeng Do you have the response object alongside with the 400 response object? Are you able to reproduce this 100% of the time? I was able to send a cast with the exact text you mentioned https://warpcast.com/~/conversations/0xf45653331e2d5c128654e9c5a09303fb4aebb979

will close for now and reopen if it happens again!
